apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-test
  namespace: nodegoat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi