apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegoat
  namespace: nodegoat
  labels:
    app: nodegoat

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nodegoat

  template:
    metadata:
      labels:
        app: nodegoat

    spec:
      containers:
      - name: nodegoat

        image: 845322645174.dkr.ecr.us-east-1.amazonaws.com/opsmx/nodegoat:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 4000

        env:
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/nodegoat

        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 15

        securityContext:
          allowPrivilegeEscalation: false