name: KICS IaC Scan
on: [pull_request]
jobs:
  kics-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@v2.1.20
        with:
          path: '.'
          output_path: kics-results/
          output_formats: ['pdf']
      - name: Show results
        run: cat kics-results/results.json
