name: Secret Scan (2MS)

on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run 2MS
        run: |
          mkdir -p artifacts

          docker run --rm \
            -v "$PWD":/repo \
            checkmarx/2ms \
            git /repo \
            --ignore-on-exit results

      - name: Check artifacts
        if: always()
        run: |
          echo "===== ARTIFACTS ====="
          ls -lah artifacts/